service: serverless-discord-bot

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2

package:
  individually: true
  exclude:
    - node_modules/**
    - slash-commands/**
    - pynacl_layer_3_9.zip
    - README.md
    - package-lock.json
    - package.json

functions:
  bot:
    handler: src/handler.main
    timeout: 15
    memorySize: 512
    url: true
    # events:
    #   - http:
    #       method: post
    #       cors: true
    #       path: lfg
    #       private: false
    environment:
      DISCORD_PUBLIC_KEY: e9955e14d08088e478ad1cb8785beb83ab31696fc74c2141cf4c85668de4f325
    layers:
      - arn:aws:lambda:eu-west-2:516399821737:layer:nacl3_9:1
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
        Resource:
          - arn:aws:dynamodb:*:516399821737:table/*

plugins:
  - serverless-iam-roles-per-function

# resources:
#   - ${file(resources/dynamodb.yml)}

# custom:
#   account:
#     dev: 516399821737
