service: serverless-discord-bot

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2

package:
  individually: true
  exclude:
    - node_modules/**
    - slash-commands/**
    - layers/**
    - README.md
    - package-lock.json
    - package.json
    - tokens.yml

functions:
  bot:
    handler: src/handler.main
    timeout: 15
    memorySize: 512
    url: true
    environment:
      DISCORD_PUBLIC_KEY: e9955e14d08088e478ad1cb8785beb83ab31696fc74c2141cf4c85668de4f325
      DISCORD_WEBHOOK_CHANNELID: 1068600560934191186
      DISCORD_WEBHOOK_TOKEN: ${file(./tokens.yml):webhooktoken}
      FOOTYAPP_URL: https://nrpl2sv57e.execute-api.eu-west-2.amazonaws.com
    layers:
      - arn:aws:lambda:eu-west-2:516399821737:layer:nacl3_9:1
      - arn:aws:lambda:eu-west-2:516399821737:layer:discord_webhook:1
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          - arn:aws:dynamodb:*:516399821737:table/*

plugins:
  - serverless-iam-roles-per-function