service: serverless-discord-bot

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2

package:
  individually: true
  exclude:
    - node_modules/**
    - slash-commands/**
    - layers/**
    - README.md
    - package-lock.json
    - package.json
    - tokens.yml

functions:
  bot:
    handler: src/handler.main
    timeout: 15
    memorySize: 512
    url: true
    environment:
      DISCORD_PUBLIC_KEY: ${file(./tokens.yml):discordpublickey}
      DISCORD_WEBHOOK_CHANNELID: ${file(./tokens.yml):webhookchannelid}
      DISCORD_WEBHOOK_TOKEN: ${file(./tokens.yml):webhooktoken}
      FOOTYAPP_URL: ${file(./tokens.yml):footyappurl}
    layers:
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:nacl3_9:1
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:discord_webhook:1
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:pandas:1
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          - arn:aws:dynamodb:*:${aws:accountId}:table/*

plugins:
  - serverless-iam-roles-per-function